2015/05/03 18:45:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login.dofit".' in C:\xampp\htdocs\DoFit\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DoFit\yii\framework\web\CController.php(270): CController->missingAction('login.dofit')
#1 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(282): CController->run('login.dofit')
#2 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login.dofi...')
#3 C:\xampp\htdocs\DoFit\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DoFit\yii\DoFit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DoFit/yii/DoFit/site/login.dofit
HTTP_REFERER=http://localhost/DoFit/yii/DoFit/site/contact.dofit
---
2015/05/03 18:56:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.damianGato".' in C:\xampp\htdocs\DoFit\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DoFit\yii\framework\web\CController.php(270): CController->missingAction('index.damianGat...')
#1 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(282): CController->run('index.damianGat...')
#2 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.dami...')
#3 C:\xampp\htdocs\DoFit\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DoFit\yii\DoFit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DoFit/yii/DoFit/site/index.damianGato
HTTP_REFERER=http://localhost/DoFit/yii/DoFit/site/page.damianGato?view=about
---
2015/05/03 18:56:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.damianGato".' in C:\xampp\htdocs\DoFit\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DoFit\yii\framework\web\CController.php(270): CController->missingAction('index.damianGat...')
#1 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(282): CController->run('index.damianGat...')
#2 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.dami...')
#3 C:\xampp\htdocs\DoFit\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DoFit\yii\DoFit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DoFit/yii/DoFit/site/index.damianGato
HTTP_REFERER=http://localhost/DoFit/yii/DoFit/site/page.damianGato?view=about
---
2015/05/03 18:56:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.damianGato".' in C:\xampp\htdocs\DoFit\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DoFit\yii\framework\web\CController.php(270): CController->missingAction('index.damianGat...')
#1 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(282): CController->run('index.damianGat...')
#2 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.dami...')
#3 C:\xampp\htdocs\DoFit\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DoFit\yii\DoFit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DoFit/yii/DoFit/site/index.damianGato
HTTP_REFERER=http://localhost/DoFit/yii/DoFit/site/page.damianGato?view=about
---
2015/05/03 18:57:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.htmdamiangato".' in C:\xampp\htdocs\DoFit\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\DoFit\yii\framework\web\CController.php(270): CController->missingAction('index.htmdamian...')
#1 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(282): CController->run('index.htmdamian...')
#2 C:\xampp\htdocs\DoFit\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.htmd...')
#3 C:\xampp\htdocs\DoFit\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\DoFit\yii\DoFit\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/DoFit/yii/DoFit/site/index.htmdamiangato
HTTP_REFERER=http://localhost/DoFit/yii/DoFit/site/login.htmdamiangato
---
2015/05/10 18:32:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 18:32:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/index".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/index')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/index
---
2015/05/10 18:33:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 18:40:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 18:40:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/index".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/index')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/index
---
2015/05/10 19:00:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 19:01:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/index".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/index')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/index
---
2015/05/10 19:01:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('login')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/login
---
2015/05/10 19:02:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/index".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/index')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/index.php
---
2015/05/10 19:03:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 19:33:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 19:33:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hola".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hola')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hola
---
2015/05/10 19:38:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hola".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hola')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hola
---
2015/05/10 19:38:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 19:38:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "viejo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('viejo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/viejo
---
2015/05/10 20:15:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 20:16:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hola".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hola')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hola
---
2015/05/10 20:18:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hola".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hola')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hola
---
2015/05/10 20:59:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 20:59:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hola".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hola')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hola
---
2015/05/10 21:00:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hola".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hola')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hola
---
2015/05/10 21:00:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/
---
2015/05/10 21:01:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo
---
2015/05/10 21:01:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hola.php".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hola.php')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hola.php
---
2015/05/10 21:26:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hola".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hola')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/dofit/aplication/index.php?r=nuevo/hola
---
2015/05/10 21:31:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hol".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hol')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/dofit/aplication/index.php?r=nuevo/hol
---
2015/05/10 21:44:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hol".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hol')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hol
HTTP_REFERER=http://localhost/dofit/aplication/nuevo/hol
---
2015/05/10 21:44:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hol".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hol')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hol
HTTP_REFERER=http://localhost/DoFit/aplication/nuevo/hol
---
2015/05/10 21:45:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hol".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hol')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hol
HTTP_REFERER=http://localhost/DoFit/aplication/nuevo/hol
---
2015/05/10 21:45:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hol".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hol')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hol
HTTP_REFERER=http://localhost/DoFit/aplication/site/login
---
2015/05/10 21:47:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hol".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hol')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hol
HTTP_REFERER=http://localhost/DoFit/aplication/site/login
---
2015/05/10 21:47:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hol".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hol')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hol
HTTP_REFERER=http://localhost/DoFit/aplication/site/login
---
2015/05/10 21:48:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "nuevo/hol".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('nuevo/hol')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/nuevo/hol
HTTP_REFERER=http://localhost/DoFit/aplication/nuevo/hol
---
2015/05/13 04:25:45 [error] [exception.CException] exception 'CException' with message 'Property "User.create_time" is not defined.' in C:\xampp\htdocs\DoFit\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\db\ar\CActiveRecord.php(145): CComponent->__get('create_time')
#1 C:\xampp\htdocs\DoFit\framework\base\CComponent.php(612) : eval()'d code(1): CActiveRecord->__get('create_time')
#2 C:\xampp\htdocs\DoFit\framework\base\CComponent.php(612): eval()
#3 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CDataColumn.php(142): CComponent->evaluateExpression('date("M j, Y", ...', Array)
#4 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridColumn.php(231): CDataColumn->getDataCellContent(0)
#5 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridColumn.php(154): CGridColumn->renderDataCellContent(0, Object(User))
#6 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridView.php(638): CGridColumn->renderDataCell(0)
#7 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridView.php(622): CGridView->renderDataCell(Object(CDataColumn), 0)
#8 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridView.php(578): CGridView->renderTableRow(0)
#9 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridView.php(488): CGridView->renderTableBody()
#10 C:\xampp\htdocs\DoFit\framework\zii\widgets\CBaseListView.php(181): CGridView->renderItems()
#11 [internal function]: CBaseListView->renderSection(Array)
#12 C:\xampp\htdocs\DoFit\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback('/{(\\w+)}/', Array, '{summary}\n{item...')
#13 C:\xampp\htdocs\DoFit\framework\zii\widgets\CBaseListView.php(149): CBaseListView->renderContent()
#14 C:\xampp\htdocs\DoFit\framework\web\CBaseController.php(181): CBaseListView->run()
#15 C:\xampp\htdocs\DoFit\aplication\protected\controllers\SiteController.php(126): CBaseController->widget('zii.widgets.gri...', Array)
#16 C:\xampp\htdocs\DoFit\framework\web\actions\CInlineAction.php(49): SiteController->actionHol()
#17 C:\xampp\htdocs\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\DoFit\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(282): CController->run('hol')
#21 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/hol')
#22 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#23 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/DoFit/aplication/site/hol
HTTP_REFERER=http://localhost/DoFit/aplication/
---
2015/05/13 04:27:24 [error] [exception.CException] exception 'CException' with message 'Property "User.create_time" is not defined.' in C:\xampp\htdocs\DoFit\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\db\ar\CActiveRecord.php(145): CComponent->__get('create_time')
#1 C:\xampp\htdocs\DoFit\framework\base\CComponent.php(612) : eval()'d code(1): CActiveRecord->__get('create_time')
#2 C:\xampp\htdocs\DoFit\framework\base\CComponent.php(612): eval()
#3 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CDataColumn.php(142): CComponent->evaluateExpression('date("M j, Y", ...', Array)
#4 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridColumn.php(231): CDataColumn->getDataCellContent(0)
#5 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridColumn.php(154): CGridColumn->renderDataCellContent(0, Object(User))
#6 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridView.php(638): CGridColumn->renderDataCell(0)
#7 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridView.php(622): CGridView->renderDataCell(Object(CDataColumn), 0)
#8 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridView.php(578): CGridView->renderTableRow(0)
#9 C:\xampp\htdocs\DoFit\framework\zii\widgets\grid\CGridView.php(488): CGridView->renderTableBody()
#10 C:\xampp\htdocs\DoFit\framework\zii\widgets\CBaseListView.php(181): CGridView->renderItems()
#11 [internal function]: CBaseListView->renderSection(Array)
#12 C:\xampp\htdocs\DoFit\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback('/{(\\w+)}/', Array, '{summary}\n{item...')
#13 C:\xampp\htdocs\DoFit\framework\zii\widgets\CBaseListView.php(149): CBaseListView->renderContent()
#14 C:\xampp\htdocs\DoFit\framework\web\CBaseController.php(181): CBaseListView->run()
#15 C:\xampp\htdocs\DoFit\aplication\protected\controllers\SiteController.php(126): CBaseController->widget('zii.widgets.gri...', Array)
#16 C:\xampp\htdocs\DoFit\framework\web\actions\CInlineAction.php(49): SiteController->actionHol()
#17 C:\xampp\htdocs\DoFit\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\DoFit\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\DoFit\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(282): CController->run('hol')
#21 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('site/hol')
#22 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#23 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/DoFit/aplication/site/hol
HTTP_REFERER=http://localhost/DoFit/aplication/
---
2015/06/02 02:46:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/gridViewStyle/images/gr-view.png".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('css/gridViewSty...')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/css/gridViewStyle/images/gr-view.png
HTTP_REFERER=http://localhost/DoFit/aplication/site/hol
---
2015/06/02 02:46:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/gridViewStyle/images/gr-update.png".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('css/gridViewSty...')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/css/gridViewStyle/images/gr-update.png
HTTP_REFERER=http://localhost/DoFit/aplication/site/hol
---
2015/06/02 02:46:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "css/gridViewStyle/images/gr-delete.png".' in C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\DoFit\framework\web\CWebApplication.php(141): CWebApplication->runController('css/gridViewSty...')
#1 C:\xampp\htdocs\DoFit\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\DoFit\aplication\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/DoFit/aplication/css/gridViewStyle/images/gr-delete.png
HTTP_REFERER=http://localhost/DoFit/aplication/site/hol
---
